{{- if eq .Values.rbac.type "namespaced" -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: aws-secret-operator
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  verbs:
  - '*'
- apiGroups:
  - mumoshu.github.io
  resources:
  - '*'
  verbs:
  - '*'
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: aws-secret-operator
subjects:
- kind: ServiceAccount
  name: {{ include "aws-secret-operator.serviceAccountName" . }}
roleRef:
  kind: Role
  name: aws-secret-operator
  apiGroup: rbac.authorization.k8s.io
{{- end }}
{{- if eq .Values.rbac.type "cluster" -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: aws-secret-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: aws-secret-operator
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  verbs:
  - '*'
- apiGroups:
  - mumoshu.github.io
  resources:
  - '*'
  verbs:
  - '*'
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: aws-secret-operator
subjects:
- kind: ServiceAccount
  name: {{ include "aws-secret-operator.serviceAccountName" . }}
  namespace: default
roleRef:
  kind: ClusterRole
  name: aws-secret-operator
  apiGroup: rbac.authorization.k8s.io
{{- end }}
